### PR TITLE
Single file printing

### PR DESCRIPTION
**Pull request by HipyCas**
This PR changes how individuals files are printed. Discussed in issue #31.

### Changes to usage

From now on, when lsfp is ran only on a file, the file will be shown, even if it is hidden when running on the directory it lays. This closes issue #31.

### Code changes

The code changed to make this work is pretty straightforward. A new argument has been added to the `print_item` function to check wether it is a single file what it is printing, leaving the function signature like the following:

```rust
21 | fn print_item(root: &path::Path, path: path::PathBuf, flags: &args::Flags, single_item: bool)
```

This new argument is then used in the conditional that checks if it is hidden, which now only turns out to be positive if that argument is set to false. The new conditional is as follows:

```rust
22 | if !flags.all && file_detection::is_hidden(&path) && !single_item {
```

### Notes on commits

Commit 4335005ae28cfa07faffa299782b7afa77de9335 should actually have not happened, as it fixes an error that was previously fixed, but risen again due to me using a wrong version of the code. The last commit, 85ba65e02e6af3cd136374f109b0910eaf0d9c4e, brings main.rs back to the latest code in master, and therefore the change made in the previous commit is not needed, so the commit also reverts that change.

### CODE REVIEW

**Review by The-Noah — APPROVED** [review]
LGTM

**Comment by The-Noah** [comment]
Just noticed the linting error: https://github.com/The-Noah/lsfp/pull/35/checks?check_run_id=2375457938#step:4:14

**Comment by HipyCas** [comment]
You are completely right. I worked on an older version of master, and when I fixed the conflicts I forgot to update the changes from master. I'll fix it between today and tomorrow.

**Comment by HipyCas** [comment]
The issue is fixed and should be working perfectly! :smiley:

**Pull request merged**
